#!/bin/bash
# Deploy script for OAuth email fixes

echo "🚀 Deploying checkout and OAuth email fixes..."
echo ""
echo "Current commits to push:"
git log --oneline origin/main..HEAD
echo ""
echo "Files changed:"
git diff --stat origin/main..HEAD
echo ""
echo "⚠️  The GITHUB_TOKEN in Codespaces is read-only."
echo "   You need to push manually with write access."
echo ""
echo "Option 1: Use gh CLI with your credentials"
echo "  gh auth login"
echo "  gh auth refresh -h github.com -s repo"
echo "  git push origin main"
echo ""
echo "Option 2: Use Personal Access Token"
echo "  1. Create token at: https://github.com/settings/tokens"
echo "  2. Select 'repo' scope"
echo "  3. Run: git remote set-url origin https://YOUR_TOKEN@github.com/slubbles/post-content.git"
echo "  4. Run: git push origin main"
echo ""
echo "Option 3: Push from local machine"
echo "  git fetch origin"
echo "  git merge origin/main"
echo "  git push origin main"
echo ""
